### ISSUE TITLE
Rename `tokio_total_seal_operations` to `tokio_total_steal_operations`

### ISSUE THREAD

**Issue by SavDont** [Hanaasagi/tokio-metrics-collector#20]
Hi, I noticed that there might be a typo in the `tokio_total_seal_operations` metric. I'm happy to make this change myself if there are any contribution guidelines to adhere to.

**Comment by SavDont** [comment]
Nevermind! This looks like it is fixed but there is no release that applies the fix. Not urgent but wondering when this change would make it into a release?

**Comment by Hanaasagi** [comment]
Sorry for the delay, a new version has been released.
